## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

script:
  - julia --color=yes -e 'if VERSION < v"0.7.0-DEV.5183"; Pkg.clone(pwd()); Pkg.checkout("${JL_PKG}", "julia-0.6"); Pkg.build("${JL_PKG}"); else using Pkg; Pkg.build(); end'
  - julia --color=yes --check-bounds=yes -e 'if VERSION < v"0.7.0-DEV.5183"; Pkg.test("${JL_PKG}", coverage=true); else using Pkg; Pkg.test(coverage=true); end'

# push coverage results to Codecov
after_success:
  - julia -e 'cd(Pkg.dir("${JL_PKG}")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
