title: ComfyCommons.jl
email: 
description: Get comfortable with these awesome Julia utilities!
github_username: mirkobunse

show_downloads: false
toc: true

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
